spring.application.name=rate-limiter-tokenbucket-API

# Server configuration
server.port=8080

# Rate limiter configuration
rate-limiter.capacity=5
rate-limiter.refill-tokens=5
rate-limiter.refill-interval-ms=60000
rate-limiter.max-retries=10

# Datasource configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 console enabled
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
